version: '1.0.{build}'

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 16 2019" ..\src\

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\tests.exe'
